### ISSUE TITLE
Task#8

### ISSUE THREAD

**Issue by irenkart** [ikolodiazhnyi/internship#3]
`blank=False, null=False` - можно не прописывать, т.к. эти значения по умолчанию являются False. Их стоит прописывать только когда вы хотите сделать `blank=True, null=True`

**Comment by ikolodiazhnyi** [comment]
> `blank=False, null=False` - можно не прописывать, т.к. эти значения по умолчанию являются False. Их стоит прописывать только когда вы хотите сделать `blank=True, null=True`

Поправил! :)
